# Generated by Django 5.0.4 on 2024-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_recipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Общая калорийность'),
        ),
    ]
