# Generated by Django 5.0.4 on 2024-04-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Аллерген')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Включены завтраки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='Включены дессерты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Включены ужины'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Включены обеды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orderapp.allergy', verbose_name='Категория (аллергия)'),
        ),
    ]
