# Generated by Django 5.0.4 on 2024-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_allergy_subscription_breakfast_subscription_dessert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='allergy',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='grams',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='калории'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Единица измерения (Количество)'),
        ),
    ]
