# Generated by Django 5.0.4 on 2024-04-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_rename_category_product_allergy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Meal',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='menus',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to='orderapp.meal', verbose_name='Категория (Время дня)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipies', to='orderapp.menu', verbose_name='Типы меню'),
        ),
    ]
