# Generated by Django 5.0.4 on 2024-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_remove_customuser_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='Единица измерения (Количество)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Категория (Время дня)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='months',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('12', '12')], default='1', max_length=100, verbose_name='Количество месяцев'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='persons',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=100, verbose_name='Количество персон'),
        ),
    ]
